### ISSUE TITLE
Remove the UC seal from the UC Santa Cruz logo

### ISSUE THREAD

**Issue by knice** [welchp/Campus-Map-Application#1]
We no longer use the UC seal when we put the UCSC logo on a website. You can use a logo without the UC seal.

![screen-2019-07-15-162410](https://user-images.githubusercontent.com/36719/61255353-0fa6f180-a71d-11e9-8ae8-1043f050f0bc.jpg)

**Comment by welchp** [comment]
Downloaded new logo kit from UCSC website. Adjusted path in app.

![image](https://user-images.githubusercontent.com/13696865/61336220-611ab380-a7e5-11e9-867a-7c90862ee9e6.png)
